import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from './_lib/utils'
import AuthProvider from './_providers/auth'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  ...rest
}: Readonly<{
  children: React.ReactNode
}>) {
  console.log('RootLayout', rest)
  return (
    <html lang="en">
      <AuthProvider>
        <body className={cn(inter.className, 'bg-slate-950 text-gray-100')}>
          {children}
        </body>
      </AuthProvider>
    </html>
  )
}
